### ISSUE TITLE
Decide on a license

### ISSUE THREAD

**Issue by rkujawa** [Sakura-IT/ReWarp#1]
The code is publicly available but no license terms accompany it. This prevents any formal release and potentially can create a legal problem.

**Comment by rkujawa** [comment]
@DvdBoon since you are the author, I believe you should decide something here. The two common options in open source world are BSD license (2-clause version for new project, equivalent with MIT license), or GNU GPL (particularly LGPL would be a better choice for a library, because it does not enforce the same license for software using it).

**Comment by DvdBoon** [comment]
As I don't know anything on the topic, I go with your advice, so let's go for the LGPL license.

**Comment by DvdBoon** [comment]
Hmm, I answered but I guess it disappeared in a big hole.

I agree with your advice. Let's go for the LGPL license.

**Comment by DvdBoon** [comment]
Of course, now it is double :-D

**Comment by rkujawa** [comment]
GNU LGPL 3.0 text imported in 997994344c062d61dbb5c7bc0ffd85fe743b98b7.

**Comment by DvdBoon** [comment]
At the moment working with Daniel/Daytona to fix issues in Warp3D which
popped up while using ReWarp. One is a lockup, the other artifacts. Both
seem to be resolved very soon regarding voodoo and Radeon 9200.
Unfortunately, somebody else is responsible for the Southern Island drivers
(Hans de Ruiter) but that could be a next step. He already offered help.
Fun to see all the effort.
Op 23 mei 2016 20:12 schreef "Radosław Kujawa" <notifications@github.com>:

Closed #1 <https://github.com/Sakura-IT/ReWarp/issues/1>.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/Sakura-IT/ReWarp/issues/1#event-669231167>

**Comment by rkujawa** [comment]
Ack although this comment added automatically to issue #1 since you replied mail that was associated with it ;). You might want to create a separate issue for this.
